server:
  port: 8083

spring:
  application:
    name: cart-service
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mahabaleshwer_mart_carts}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}

# Application Specific Configuration
app:
  cart:
    session-timeout: ${CART_SESSION_TIMEOUT:1800} # 30 minutes in seconds
    max-items: ${CART_MAX_ITEMS:50}
    cache:
      ttl: ${CART_CACHE_TTL:1800} # 30 minutes in seconds
