server:
  port: 8085

spring:
  application:
    name: notification-service
  
  # Kafka Configuration (RabbitMQ disabled)
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    consumer:
      group-id: notification-service
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "com.mahabaleshwermart.common.events"
      enable-auto-commit: false
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      acks: all
      retries: 3
    listener:
      ack-mode: manual_immediate
  
  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Application Specific Configuration
app:
  notification:
    email:
      from: ${NOTIFICATION_EMAIL_FROM:noreply@mahabaleshwermart.com}
      templates-path: ${EMAIL_TEMPLATES_PATH:/templates/email}
    sms:
      enabled: ${SMS_ENABLED:false}
      provider: ${SMS_PROVIDER:twilio}
      api-key: ${SMS_API_KEY:}
    push:
      enabled: ${PUSH_ENABLED:false}
      fcm-key: ${FCM_KEY:}
