server:
  port: 8081

spring:
  application:
    name: user-service
  
  # Database Configuration
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:mahabaleshwer_mart_users}?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: false
  
  # Redis Configuration
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  
  # Mail Configuration
  mail:
    host: ${MAIL_HOST:smtp.gmail.com}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
  access-token-expiration: ${JWT_ACCESS_EXPIRATION:86400000} # 24 hours
  refresh-token-expiration: ${JWT_REFRESH_EXPIRATION:604800000} # 7 days

# Application Specific Configuration
app:
  security:
    allowed-origins:
      - "http://localhost:4200"
      - "http://localhost:3000"
      - "https://mahabaleshwermart.com"
  
  email:
    verification:
      enabled: ${EMAIL_VERIFICATION_ENABLED:false}
      expiration: 3600 # 1 hour in seconds
  
  rate-limiting:
    enabled: true
    requests-per-minute: 60
